### ISSUE TITLE
How is entropy accumulated?

### ISSUE THREAD

**Issue by englehardt** [bslassey/privacy-budget#4]
It's a little unclear to me how you plan to accumulate entropy for enforcement. You say:

> This is yet another measurement step where each browser can use the data collected in the previous step to account for the total information exposed to each site and report that back through telemetry. [...] This measurement will need to include the entirety of a user's interaction with a domain, until site data is cleared.

I take this to mean that entropy is accumulated (and the budget enforced) per top-level origin. That is, all API access that occurs in the main context, in iframes, and in nested iframes will count towards the top-level origin's budget, and this budget will accumulate across all page visits to that top-level origin until the user (or browser) clears state. Is that correct?

**Comment by bslassey** [comment]
Yes, that is how I intended it. If you have wording to make that more clear, I'll gladly take a PR.

**Comment by bslassey** [comment]
@englehardt I'm going to close this out, but if you have a suggestion to clear up the language please open a PR.
